name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Check .next folder before deploy
        run: |
          if [ ! -d ".next" ] || [ -z "$(ls -A .next)" ]; then
            echo ".next folder is empty. Build failed or nothing to deploy."
            exit 1
          fi

      - name: Deploy to Server via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: ".next/*"
          script: |
            cd ~/japanese-learning/frontend_jlpt_learn/
            git pull origin main
            npm install --legacy-peer-deps
            npm run build
            pm2 restart 11